* Camel

** [[https://en.wikipedia.org/wiki/Camel_(band)][Camel]]

[[https://en.wikipedia.org/wiki/Camel_(band)#Discography][Discografia]]

- Camel (1973)
- Mirage (1974)
- The Snow Goose (1975)
- Moonmadness (1976)
- Rain Dances (1977)
- Breathless (1978)
- I Can See Your House from Here (1979)
- Nude (1981)
- The Single Factor (1982)
- Stationary Traveller (1984)
- Dust and Dreams (1991)
- Harbour of Tears (1996)
- Rajaz (1999)
- A Nod and a Wink (2002)


** Álbuns favoritos

*** *Camel*:
Do primeiro álbum gosto muito das músicas: [[https://www.youtube.com/watch?v=JPEUfUCKHVQ][Never Let Go]] e [[https://www.youtube.com/watch?v=IHwBD-s4NJA][Curiosity]].

*** *Mirage*:
O clássico do Camel. Duas das minhas músicas favoritas do Camel estão nesse álbum:
[[https://www.youtube.com/watch?v=keu5fRyRtNw][Lady Fantasy]] e [[https://www.youtube.com/watch?v=aPenjGbLtLU][The White Rider]] que é uma música sobre Gandalf:

#+begin_quote
Once he wore grey, he fell and slipped away\\
From everybody's sight.\\
The wizard of them all, came back from his fall\\
This time wearing white.
#+end_quote

A capa desse álbum é o desenho da embalagem do cigarro Camel.

*** *Snow Goose*:
Álbum instrumental conceitual baseado no romance [[https://en.wikipedia.org/wiki/The_Snow_Goose_(novella)][The Snow Goose]].
Nunca li o livro, mas já ví o [[https://www.youtube.com/watch?v=1pwwZOGN-ao][filme de 1971]], que tem disponível no Youtube. Recomendo.

*** *Moonmadness*:
Meu álbum favorito do Camel, duas obras de arte: [[https://www.youtube.com/watch?v=DbG7KDyr0Ck][Another Night]] e [[https://www.youtube.com/watch?v=SbaG74lsk-o][Air Born]]. 

