#+TITLE: O Rebelde Aristocrata - Losurdo
#+AUTHOR: Thiago Araujo
#+YEAR: 2026

* *Cap 1*
** 1.1 & 1.2
Losurdo argumenta como O Nascimento da Tragédia é um livro político, e
toda a interpretação desse livro como um louvor a Wagner ou uma ode à
arte perde uma grande parcela do seu significado.

Niezsche faz uma crítica a moleza da sociedade moderna idealizando uma
sociedade grega idealizada (ele reconhece não ser historia) que
reconhecia a tragédia. Com isso, ele critica a herança filosófica de
Sócrates e Platão como algo não grego e não virial.  Na raiz, essa é
uma crítica a ideais de igualdade. É uma crítica ao socialismo.

Inicialmente Nietzsche critica a serenidade que era imaginado na
sociedade grega. Nesse aspecto Nietzsche nào era pioneiro.  Sendo
assim, ele inicialmente elogiava o pessimismo da tragédia grega.  Em
algum momento Nieztsche rompe com Wagner e com Schoppenhauer e inicia
uma crítica ao otimismo grego. Ele declara que a tragédia é uma prova
de que os gregos não eram pessimistas, e sim otimistas.
